/*
* generated by Xtext
*/
package com.concur.babel.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractBabelIdlJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.concur.babel.babelIdl.BabelIdlPackage.eINSTANCE);
		return result;
	}

}
