/*
* generated by Xtext
*/
package com.concur.babel;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BabelIdlUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.concur.babel.ui.internal.BabelIdlActivator.getInstance().getInjector("com.concur.babel.BabelIdl");
	}
	
}
