/*
 * generated by Xtext
 */
package com.concur.babel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BabelIdlUiModule extends com.concur.babel.ui.AbstractBabelIdlUiModule {
	public BabelIdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends org.eclipse.xtext.ui.editor.contentassist.IContentProposalProvider> bindIContentProposalProvider() {
		return com.concur.babel.ui.contentassist.BabelIdlProposalProvider.class;
	}	
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
		return BabelHighlightingConfiguration.class;
	}
	
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator(){
		return BabelHighlightingCalculator.class;
	}	 	
	
}
