/*
 * generated by Xtext
 */
package com.concur.babel.validation

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class BabelIdlValidator extends AbstractBabelIdlValidator {

//    @Check
//    def checkEnumNamesAreUnique(com.concur.babel.babelIdl.Enum enumObj) {
//        
//        val names = new HashSet<String>();
//        for (EnumProperty p : enumObj.properties) {
//            names.add(p.name.name)
//        }
//        
//        for (EnumProperty p : enumObj.properties) {
//            if (names.contains(p.name.name)) {
//                System.err.println("bbbbbbaaadddd!!! " + p.name.name)
//            }
//        }
//        
//    }

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
}
