/*
 * generated by Xtext
 */
package com.concur.babel;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BabelIdlRuntimeModule extends com.concur.babel.AbstractBabelIdlRuntimeModule {
	
}
