/*
* generated by Xtext
*/
package com.concur.babel.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.concur.babel.services.BabelIdlGrammarAccess;

public class BabelIdlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BabelIdlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.concur.babel.parser.antlr.internal.InternalBabelIdlParser createParser(XtextTokenStream stream) {
		return new com.concur.babel.parser.antlr.internal.InternalBabelIdlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "BabelIdl";
	}
	
	public BabelIdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BabelIdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
