/**
 * generated by Xtext
 */
package com.concur.babel.validation;

import com.concur.babel.validation.AbstractBabelIdlValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class BabelIdlValidator extends AbstractBabelIdlValidator {
}
