/*
 * generated by Xtext
 */
package com.concur.babel.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.concur.babel.ui.internal.BabelIdlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BabelIdlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BabelIdlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BabelIdlActivator.getInstance().getInjector(BabelIdlActivator.COM_CONCUR_BABEL_BABELIDL);
	}
	
}
